quartz:
  enabled: true
server:
  port: 9090
spring:
  application:
    name: Spring-Quartz-Scheduler   # Quartz调度中心
  datasource:
    url: jdbc:mysql://120.78.134.111:3306/job_entity?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
